name: Build and publish release

on:
  push:
    tags:
      - 'v*'

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: ['16', '18']
        redis-version: [6]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          registry-url: 'https://npm.pkg.github.com'

      - name: Start Redis
        uses: supercharge/redis-github-action@1.4.0
        with:
          redis-version: ${{ matrix.redis-version }}

      - name: Install Packages
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Run Tests
        run: npm run test

      - name: Bundle
        run: npm run compile
        if: ${{ matrix.node-version == 16 }}

      - run: npm publish
        if: ${{ matrix.node-version == 16 }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
